# Add 'label1' to any changes within 'example' folder or any subfolders
documentation: README.md

dependencies: package.*

# Add 'label2' to any file changes within 'example2' folder
test-changes:
  - test/**/*


github-actions:
  - .github/**/*

circleci-actions:
  - .circleci/**/*

enhancement:
  - src/**/*
