# Add 'label1' to any changes within 'example' folder or any subfolders
documentation: README.md

# Add 'label2' to any file changes within 'example2' folder
test:
  - test/**/*

github-actions:
  - .github/**/*
