version: 2
jobs:
  build_and_test:
    working_directory: ~/mern-starter
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node:latest
      # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: ./node_modules/.bin/nyc report --reporter=json
      - run:
          name: send code coverage to codecov
          command: ./node_modules/.bin/codecov

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
