#!/usr/bin/env bash

set -ex

PATH=/usr/local/share/.config/npm/global/node_modules/.bin:$PATH

if [[ "$CIRCLE_BRANCH" != greenkeeper/* ]]; then
  npm install
  exit 0
fi

if [[ ! -z "$GIT_EMAIL" ]] & [[ ! -z "$GIT_USERNAME" ]]; then
  git config --global push.default simple
  git config --global user.email "$GIT_EMAIL"
  git config --global user.name "$GIT_USERNAME"
fi

if [[ ! -x "$(command -v greenkeeper-lockfile-update)" ]]; then
  npm install -g greenkeeper-lockfile@1
fi

greenkeeper-lockfile-update
npm install
greenkeeper-lockfile-upload
